### PR TITLE
Add support for Teensy 3.5/3.6

### PR DESCRIPTION
**Pull request by wilywampa**
Clean up the nested if/else around the version option and add support for Teensy 3.5 and 3.6.

### CODE REVIEW

**Comment by apmorton** [comment]
Hello, thanks for the contribution.

Will the teensy 3.5/3.6 work with the current version of the teensy core files in this repo, or do we need to update those as well?

**Comment by wilywampa** [comment]
The core files need to be updated as well - sorry, sort of forgot I had done that in my project.

**Comment by apmorton** [comment]
@wilywampa Thanks for the contribution - please let me know if something didn't go right with the latest master branch.  I have updated the teensy3 core files from the latest release (1.31), but I was not able to update the tools since I don't have access to a linux machine at this moment to run the GUI installer on.

If any of the binaries in the tools folder need to be updated, please let me know!

**Comment by wilywampa** [comment]
@apmorton The only change that needs to be made for sure is `teensy3/main.cpp` should be deleted so there aren't two definitions of `main()`. The tools are different but it works without updating them and I'm not sure if they're different because I'm on OSX or because they need to be updated. Thanks again.

**Comment by apmorton** [comment]
@wilywampa thanks for the heads up about main.cpp in the teensy3 folder - I forgot that should not be added.  Fixed in master.  I will open an issue to hopefully remind myself that the tools folder needs to at the very least be checked to see if an update is needed.

**Pull request merged**
