### PR TITLE
Updating build script for OSX version of Teensyduino (paths have appa…

### PR DESCRIPTION
**Pull request by thebiguno**
…rently changed since the original version?)

It looks like the tool paths for OSX version of Arduino / Teensyduino have changed (not sure when, but the paths are definitely incorrect for 1.6.4 and 1.6.5).  This pull request fixes the paths for OSX.  I have also tested on Linux and it does not appear to break anything, but an extra confirmation is probably warranted.

On a separate note, do you have plans to add support for Teensy-LC?  If not, I will try to do so myself (there is no point if you are already planning on this).

Cheers

### CODE REVIEW

**Comment by thebiguno** [comment]
(Another commit just pushed to fix the teensy loader path on OSX.)

**Comment by apmorton** [comment]
can you take a look at master?

I updated the included tools for teensyduino 1.24, along with updating the teensy3 core to the latest commit.

I also added support for teensy LC. It compiles, but I have not tested it on a device because I don't have an LC here.

**Comment by thebiguno** [comment]
Cool, thanks!  Much closer, but there is still an extra "Resources" in the path.  You have:

TOOLSPATH = /Applications/Arduino.app/Contents/Resources/Java/hardware/tools/
where it should be:
TOOLSPATH = /Applications/Arduino.app/Contents/Java/hardware/tools/

I can make another pull request if you want, although it is probably easier to just do the change manually.

As for LC support, I will try it this evening on my home Linux box with a Teensy-LC and report back.

**Comment by apmorton** [comment]
yep, fixed in master. thanks for pointing that out

**Comment by thebiguno** [comment]
Yep, I can confirm that the fix works on OSX.  Thanks!

I'll try out LC tonight and let you know.  In the mean time, this pull request is completed. :-)

Cheers

**Comment by thebiguno** [comment]
Just to follow up... I have verified that the Teensy LC works under both OSX and Linux using the newest version of your Makefile.  Thank you very much for your help, and for sharing such great code (not just this, I am also a huge fan of your python / rawhid bindings, and am using them in a few different projects).

Cheers

**Pull request closed without merging**
